---
-
  get_url:
    dest: /home/{{user_name | quote }}
    description: "It will clone the woocommerce script from repository"
    group: "{{user_name | quote }}"
    mode: 493
    owner: "{{user_name | quote }}"
    url: "https://raw.githubusercontent.com/asift91/ansiblewp/master/woocommerce.sh"
  name: "Download woocommerce script using get_url"
-
  name: "Run a woocommerce script with arguments (using 'cmd' parameter)"
  description: "It will run the cloned script"
  shell: /home/{{user_name | quote }}/woocommerce.sh {{domain_name | quote }} {{user_name |quote }}
  args:
    executable: /bin/bash
